### ISSUE TITLE
error

### ISSUE THREAD

**Issue by maximuml** [DASPRiD/vnstat-php#1]
2016/02/13 10:42:40 [error] 18218#18218: *1659 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined offset: -1 in /var/www/vnstat-php-master/index.php on line 41" while reading upstream, client: 192.168.1.36, server: 192.168.1.34, request: "GET /vnstat-php-master/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.1.34"
2016/02/13 10:42:40 [error] 18218#18218: *1659 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined offset: -1 in /var/www/vnstat-php-master/index.php on line 41" while reading upstream, client: 192.168.1.36, server: 192.168.1.34, request: "GET /vnstat-php-master/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.1.34"

**Comment by DASPRiD** [comment]
Can you send me the output of ```vnstat --dumpdb```? Also, are you using the latest master?

**Comment by maximuml** [comment]
> version;3
active;1
interface;p1p1
nick;p1p1
created;1435308993
updated;1455367223
totalrx;3896
totaltx;64865
currx;932591616
curtx;10690739200
totalrxk;957
totaltxk;57
btime;1455051873
d;0;1455310818;291;355;910;790;1
d;1;1455224409;127;2530;681;303;1
d;2;1455138001;108;755;532;895;1
d;3;1455051629;361;6553;542;792;1
d;4;1455035757;634;20360;950;317;1
d;5;1454360402;1575;8999;740;298;1
d;6;1454274023;60;107;258;752;1
d;7;1454187614;178;3556;1018;884;1
d;8;1454101205;428;16595;229;951;1
d;9;1454066221;128;5040;977;522;1
d;10;1438006951;0;2;62;860;1
d;11;1436666798;0;5;201;882;1
d;12;1435308993;0;0;1;3;1
d;13;0;0;0;0;0;0
d;14;0;0;0;0;0;0
d;15;0;0;0;0;0;0
d;16;0;0;0;0;0;0
d;17;0;0;0;0;0;0
d;18;0;0;0;0;0;0
d;19;0;0;0;0;0;0
d;20;0;0;0;0;0;0
d;21;0;0;0;0;0;0
d;22;0;0;0;0;0;0
d;23;0;0;0;0;0;0
d;24;0;0;0;0;0;0
d;25;0;0;0;0;0;0
d;26;0;0;0;0;0;0
d;27;0;0;0;0;0;0
d;28;0;0;0;0;0;0
d;29;0;0;0;0;0;0
m;0;1454274023;3160;39663;517;51;1
m;1;1454066221;736;25193;176;309;1
m;2;1436666798;0;8;263;718;1
m;3;1435308993;0;0;1;3;1
m;4;0;0;0;0;0;0
m;5;0;0;0;0;0;0
m;6;0;0;0;0;0;0
m;7;0;0;0;0;0;0
m;8;0;0;0;0;0;0
m;9;0;0;0;0;0;0
m;10;0;0;0;0;0;0
m;11;0;0;0;0;0;0
t;0;1455035757;634;20360;950;317;1
t;1;1454101205;428;16595;229;951;1
t;2;1454360402;1575;8999;740;298;1
t;3;1455051629;361;6553;542;792;1
t;4;1454066221;128;5040;977;522;1
t;5;1454187614;178;3556;1018;884;1
t;6;1455224409;127;2530;681;303;1
t;7;1455138001;108;755;532;895;1
t;8;1454274023;60;107;258;752;1
t;9;1436666798;0;5;201;882;1
h;0;1455314388;3444;3994
h;1;1455317988;5080;84507
h;2;1455321589;2987;20605
h;3;1455325189;2415;2668
h;4;1455328789;2414;2671
h;5;1455332390;2413;2648
h;6;1455335990;9707;70707
h;7;1455339591;4500;80053
h;8;1455343191;2450;2670
h;9;1455346791;3038;21876
h;10;1455350392;21116;41440
h;11;1455353992;64469;8548
h;12;1455357592;30521;5892
h;13;1455361193;139446;9816
h;14;1455364793;2883;3028
h;15;1455367223;2011;3187
h;16;1455285585;3473;36198
h;17;1455289186;2887;3293
h;18;1455292786;4881;87275
h;19;1455296386;2926;12637
h;20;1455299987;2574;2802
h;21;1455303587;2729;7125
h;22;1455307187;2643;2868
h;23;1455310788;2647;5635

Yes, latest master.

**Comment by DASPRiD** [comment]
I just tested with your data, and it works fine. Are you using another interface via the new config (as in: is "p1p1" actually the interface vnstat-php uses)? If so, I'd need the vnstat dump of that different interface.
