### ISSUE TITLE
No content was displayed

### ISSUE THREAD

**Issue by flipphos** [DASPRiD/vnstat-php#2]
Hi, I tried your vnstat-php script on my VPS (Centos 6.9), which has Nginx: 1.12.1, MySQL: 5.5.36, PHP:5.5.38 as environment.

The php-frontend only shows two lines with "Network Traffic" and "Hourly", and nothing else, as shown in the attached picture. I tried under Safari 11.0.2 and Firefox 57.0.1, same results.

<img width="973" alt="default" src="https://user-images.githubusercontent.com/11366098/33945182-3e75e124-e059-11e7-87c6-3d69f5eedf90.png">

While vnstati gives the following picture:
![default](https://user-images.githubusercontent.com/11366098/33945359-c361f724-e059-11e7-8134-55e21dea808f.png)

**Comment by DASPRiD** [comment]
This is weird, any messages in the PHP/Nginx error log?

**Comment by flipphos** [comment]
Sorry for not replying you earlier.
I was trying to solve this problem. It appeared that 'shell_exec" was disabled in the php.ini. I fixed it and now the script runs beautifully.
Thank you very much for your prompt response and nice contribution!

**Comment by cantalupo555** [comment]
I am using apache server, I am having this problem, white screen.
php7

`[Tue Jul 10 18:50:00.907303 2018] [:error] [pid 2214] [client 187.33.231.61:25962] PHP Fatal error:  Uncaught Error: Class 'IntlDateFormatter' not found in /var/www/html/status/2/index.php:55\nStack trace:\n#0 {main}\n  thrown in /var/www/html/status/2/index.php on line 55
[Tue Jul 10 18:50:51.842461 2018] [:error] [pid 2215] [client 187.33.231.61:30690] PHP Fatal error:  Uncaught Error: Class 'IntlDateFormatter' not found in /var/www/html/status/2/index.php:55\nStack trace:\n#0 {main}\n  thrown in /var/www/html/status/2/index.php on line 55
[Tue Jul 10 18:50:53.367632 2018] [:error] [pid 1921] [client 187.33.231.61:15976] PHP Fatal error:  Uncaught Error: Class 'IntlDateFormatter' not found in /var/www/html/status/2/index.php:55\nStack trace:\n#0 {main}\n  thrown in /var/www/html/status/2/index.php on line 55
[Tue Jul 10 18:51:49.969089 2018] [:error] [pid 1957] [client 187.33.231.61:24844] PHP Fatal error:  Uncaught Error: Class 'IntlDateFormatter' not found in /var/www/html/status/2/index.php:55\nStack trace:\n#0 {main}\n  thrown in /var/www/html/status/2/index.php on line 55
[Tue Jul 10 18:51:51.480070 2018] [:error] [pid 1920] [client 187.33.231.61:40732] PHP Fatal error:  Uncaught Error: Class 'IntlDateFormatter' not found in /var/www/html/status/2/index.php:55\nStack trace:\n#0 {main}\n  thrown in /var/www/html/status/2/index.php on line 55`
![](https://i.imgur.com/MpQXfpo.png)
