### ISSUE TITLE
php 7.4

### ISSUE THREAD

**Issue by maximuml** [DASPRiD/vnstat-php#6]
Hi.
I get this error with php7.4

`2020/04/14 06:36:05 [error] 130428#130428: *16 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'IntlDateFormatter' not found in /var/www/vnstat-php/index.php:55
Stack trace:
#0 {main}
thrown in /var/www/vnstat-php/index.php on line 55" while reading response header from upstream, client: 85.##, server: 162.##, request: "GET /vnstat-php/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "162.##"
`

Any suggestions? Thanks

**Comment by DASPRiD** [comment]
You need to install the `intl` PHP extension.

**Comment by maximuml** [comment]
It's installed, but nothing

**Comment by DASPRiD** [comment]
Then you have probably not enabled it for your fpm process.

**Comment by maximuml** [comment]
Working fine on php7.2
